---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: mi-api
  ports:
    - protocol: TCP
      port: 80    # Puerto externo
      targetPort: 4000  # Puerto del contenedor
  type: LoadBalancer  # Balanceador de carga externo
